Strip dashes from accountPin for Verizon donors
gigs/embeds-js pull request #92
Opened 2024-08-08 15:38 UTC by Plsr

### Rationale

We have recently learned that Verizon will display their users account PINs with dashes (e.g. 123-456) for better readability, but actually requires the PIN to be sent without dashes for port outs.
Naturally, this cause users to copy the PIN in the format provided by Verizon, causing failed portings.

We have adapted [Connect](https://gigs.com/connect) to automatically strip dashes from the accountPin field in the porting form for Verizon portings and decided to backport this functionality to our other products as well.

### Changes
`<StepCarrierDetailsForm />` defines a new function (outside of the component), `normalizeAccountPin`, which handles the removal of dashes in case the `donorProvider` is "Verizon". The trimming that was done in `onSubmit` before has been moved into this function as well.

2024-08-08 16:27 UTC, timomeh requested changes

2024-08-08 16:27 UTC, timomeh commented on lib/PortingEmbed/StepCarrierDetailsForm.tsx
Could you add a test for this behavior into `StepCarrierDetailsForm.test.tsx`? There are already some tests for data transformation of the accountPin in there, would be a bit odd if it's only tested in the `PortingForm` but not specific in the `StepCarrierDetailsForm`

2024-08-09 06:29 UTC, Plsr commented on lib/PortingEmbed/StepCarrierDetailsForm.tsx
Oh yeah of course. Completely stopped looking for other tests when I saw the business logic was tested in `PortingForm.test.tsx`

2024-08-09 08:19 UTC, timomeh requested changes

2024-08-09 08:19 UTC, timomeh commented on lib/PortingEmbed/__tests__/StepCarrierDetailsForm.test.tsx
> +        }}
Let's use [fishery](https://github.com/thoughtbot/fishery) here to build the donorProvider fixture, like we're using fishery for all other data fixtures. You don't have to write and merge the data yourself, and if the fixtures change in the future, it's less work to change them everywhere

```tsx
const donorProvider = serviceProviderFactory.build({ name: 'Verizon' })
const porting = portingFactory
  .association({ donorProvider })
  .build({ required: ['accountPin'] })

render(<StepCarrierDetailsForm porting={porting} />)
```

2024-08-09 08:19 UTC, timomeh commented on lib/PortingEmbed/__tests__/PortingForm.test.tsx
> +    )
Let's also use fishery here for the fixtures

```tsx
describe('for Verizon', async () => {
  const donorProvider = serviceProviderFactory.build({ name: 'Verizon' })
  const verizonPorting = portingFactory.build(porting, { associations: { donorProvider } })

  it('strips dashes from accountPin', async () => {
    const user = userEvent.setup()
    render(<PortingForm porting={verizonPorting} /> // .....
```

2024-08-09 08:19 UTC, timomeh commented on lib/PortingEmbed/__tests__/StepCarrierDetailsForm.test.tsx
> +  it('removes dashes when submitting for Verizon donor provider', async () => {
The logic of the code is to only strip dashes for Verizon and keep them for all other providers – could we add a test to check that dashes are not stripped for other providers?

2024-08-13 08:14 UTC, Plsr commented on lib/PortingEmbed/__tests__/StepCarrierDetailsForm.test.tsx
> +        }}
Sure thing. Was contemplating to do it but thought it would be too small of a thing to justify a factory. However, if the vision is to use factories for everything I'm happy to add that!

2024-08-13 08:15 UTC, Plsr commented on lib/PortingEmbed/__tests__/StepCarrierDetailsForm.test.tsx
> +  it('removes dashes when submitting for Verizon donor provider', async () => {
I actually adapted the default test to take `123-456` as input and not change that. I can see how this might be too implicit, though. I'll add a more explicit test case!

2024-08-13 10:26 UTC, timomeh approved these changes
Awesome, thanks!

2024-08-14 12:26 UTC, merged